### ISSUE TITLE
Гугл-таблица выдаёт пустой результат

### ISSUE THREAD

**Issue by opensearch** [empenoso/SilverFir-Investment-Report#7]
Нажать "Поиск облигаций v.5",  пройти авторизацию, дождаться пока выполняется скрипт. 
Вкладка "Результат" остаётся пустой.

**Comment by empenoso** [comment]
Воспользуйтесь скриптом - там всё работает: https://github.com/empenoso/SilverFir-Investment-Report/tree/master/Node.js%20Release/bond_search_v2
